exports.basePath = "not yet set!"
exports.amazon_ws = "http://169.254.169.254/latest/meta-data/"
exports.internalDNS = "not yet set!"
exports.createMachineScript = __dirname+"/../../create_machine.sh"
exports.deleteMachineScript = __dirname+"/../../delete_machine.sh"
